language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
env:
  
script:
  - npm run build-storybook
env:
- CI=true
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1
branches:
  only:
  - /.*/ # all